-- CLIENTES QUE MORAM EM SÃO PAULO
SELECT *
FROM CLIENTES

SELECT nomes
FROM CLIENTES
WHERE cidades = 'São Paulo';

-- MOSTRE TODOS OS PEDIDOS MAIORES QUE 300
SELECT *
FROM pedidos2

SELECT *
FROM pedidos2
WHERE valores > 300.00;


-- CONTE QUATOS CLIENTES EXITEM NA TABELA CLIENTES?
SELECT COUNT (*) AS Total_Clientes
FROM CLIENTES

-- OU ASSIM
SELECT COUNT(id_clientes)
FROM CLIENTES

-- QUAL VALOR TOTAL DE TODOS OS PEDIDOS?
SELECT SUM (valores) AS Valor_Total_Pedido
FROM pedidos2


-- QUAL A MÉDIA DE VALOR DOS PEDIDOS?
SELECT AVG(valores) AS Media_Pedidos
FROM pedidos2