

-- DESCOBRIR QUANTOS PEDIDOS CADA CLIENTE FEZ ?
SELECT 
	CLIENTE.Nome,
	COUNT(*)		AS QUANTIDADE_PEDIDOS
FROM PEDIDOS
JOIN CLIENTE
	ON PEDIDOS.Cliente_id = CLIENTE.ID
GROUP BY CLIENTE.Nome
ORDER BY QUANTIDADE_PEDIDOS DESC;

--Ana pediu 2 e o João pediu 1